version: '3.4'

services:
  db:
    image: postgres:13.1
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: "${DB_PORT}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
  app:
    build: ./
    ports:
      - "3000:${PORT}"
      - "3001:${PORT_WS}"
    environment:
      DB_HOST: db
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      PORT: "${PORT}"
      PORT_WS: "${PORT_WS}"
