version: '3.4'

services:
  db:
    image: postgres:13.1
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build: ./api
    ports:
      - "3001:3001"
  web:
    build: ./web
    ports:
      - "3000:3000"
