version: '3.4'

services:
  db:
    image: postgres:13.1
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: "${DB_PORT}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
  api:
    depends_on:
      - db
    build: ./api
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
  web:
    build: ./web
    ports:
      - "3000:3000"